[package]
name = "tapip-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
etherparse = "0.16.0"
lazy_static = "1.5.0"
libc = "0.2.169"
log = "0.4.22"
logger = "0.4.0"
tun-tap = "0.1.4"
