[package]
name = "tapip-rs"
version = "0.1.0"
edition = "2021"
autoexamples = false

[dependencies]
heapless = "0.8.0"
libc = "0.2.169"
log = "0.4.22"
managed = "0.8.0"

[dev-dependencies]
env_logger = "0.11.6"
getopts = "0.2.21"
rand = "0.8.5"

[[example]]
name = "server"
